

name: Maven Test

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2


#      - name: Enable .github scripts
#        run: chmod +x .github/scripts/*.sh
#
#      - name: Decrypt .protected files
#        run: .github/scripts/decryptProtectedFiles.sh ".protected/.protected"
#        env:
#          PROTECTED_FILES_PASSPHRASE: ${{ secrets.PROTECTED_FILES_PASSPHRASE }}


      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
          server-id: github
          server-usernamne: MAVEN_ACCESS_USER
          server-password: MAVEN_ACCESS_TOKEN

      - name: Compile w/o Running Tests
        run: mvn -s maven-settings.xml --batch-mode -DskipTests package
        env:
          MAVEN_ACCESS_USER: ${{ secrets.MAVEN_ACCESS_USER }}
          MAVEN_ACCESS_TOKEN: ${{ secrets.MAVEN_ACCESS_TOKEN }}


      - name: Run Tests
        run: mvn -s maven-settings.xml --batch-mode -Dmaven.test.failure.ignore=true test
        env:
          MAVEN_ACCESS_USER: ${{ secrets.MAVEN_ACCESS_USER }}
          MAVEN_ACCESS_TOKEN: ${{ secrets.MAVEN_ACCESS_TOKEN }}

#      - name: Report
#        uses: dorny/test-reporter@v1
#        if: always()
#        with:
#          name: Maven Tests
#          path: target/surefire-reports/*.xml
#          reporter: java-junit
#          fail-on-error: true
          